# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-04 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shanmao1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wheel',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
