# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-04 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shanmao1', '0002_auto_20181204_0917'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wheel',
        ),
    ]
