# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-07 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shanmao1', '0003_delete_wheel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('information', models.CharField(max_length=100)),
                ('RMB', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('original', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
