# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-10 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shanmao1', '0005_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token',
            field=models.CharField(default='', max_length=256),
        ),
    ]
