# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-12 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shanmao1', '0007_goods_goodsid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('isselect', models.BooleanField(default=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shanmao1.Goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shanmao1.User')),
            ],
        ),
    ]
